set(PACKAGE_VERSION "1.83.0")

if(PACKAGE_FIND_VERSION_MAJOR EQUAL 1 AND PACKAGE_FIND_VERSION VERSION_LESS_EQUAL PACKAGE_VERSION)
	set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
	set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()

if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
	set(PACKAGE_VERSION_EXACT TRUE)
endif()
